### ISSUE TITLE
critical vulnerability in most jwt libraries

### ISSUE THREAD

**Issue by alexanderkjeldaas** [juretta/haskell-jwt#1]
I think this library is vulnerable too, since the Secret type is not type-safe wrt algorithm (it is possible for an attacker to change the algorithm).  

Either verify should take an additional algorithm parameter, or the Secret type should embed which algorithm it is considered a secret for.

https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/

**Comment by juretta** [comment]
Issue tracking is here and I see you already filed an issue: https://bitbucket.org/ssaasen/haskell-jwt/issue/14/critical-bug-verify-is-insecure

See my response there.
